package enums;

public enum TipodeAnimal {
    ELEFANTE, GIRAFA, HIPOPOTAMO, LEAO, ZEBRA, PINGUIM, MACACO, LEMURE, LONTRA, COBRA, ONCA_PINTADA, TIGRE, URSO, 
    LOBO, TAMANDUA, VEADO, ARARA, AVESTRUZ, CISNE, FLAMINGO, PAPAGAIO, TUCANO, PAVAO, JABUTI, JACARE , TARTARUGA;    
 
}

